import Head from 'next/head'
import Image from 'next/image'
import Project from '../components/Project'
import Home_Page from "./../components/Home_Page"
import Contact from "./Contact";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Gunpriya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home_Page />
      <Project />
      <Contact />
    </div>

  )
}

